apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kubernetes-playground
  region: us-east-1

vpc:
  id: "vpc-eb5a7f93"
  subnets:
    public:
      us-east-1a:
          id: "subnet-59ff7904"
      us-east-1b:
          id: "subnet-9af3befe"
      us-east-1c:
          id: "subnet-097af826"

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 2
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
    ssh:
      publicKeyName: eks

